<?php

namespace Infrastructure\Persistence\DoctrineODM\Task;

use Domain\Repository\TaskRepositoryInterface;
use Domain\Task;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ODM\MongoDB\DocumentRepository implements TaskRepositoryInterface
{



    /**
     * Save task
     *
     * @param Task $task Task object
     *
     * @return void
     */
    public function save(Task $task)
    {
        $this->dm->persist($task);
        $this->dm->flush();
    }

    /**
     * Find task by Id
     *
     * @param mixed $id Task id
     *
     * @return mixed|Task
     * @throws TaskNotFoundException
     */
    public function find($id): Task
    {
        return parent::find($id);
    }

    /**
     * Remove task
     *
     * @param Task $task Task object
     *
     * @return void
     */
    public function remove(Task $task)
    {
        $this->dm->remove($task);
        $this->dm->flush();
    }
}
