Domain\Task:
    type: entity
    table: tasks
    repositoryClass: Infrastructure\Persistence\Adapter\DoctrineORMAdapter
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
