services:
    task.frontend.default:
        class: Infrastructure\Delivery\Frontend\TodoBundle\Controller\DefaultController
        autowire: true
#        arguments: ['@task.create_task', '@task.list_task']

#    task.doctrine_orm.repository:
#        class: Infrastructure\Persistence\DoctrineORM\Task\TaskRepository
#        factory: ['@doctrine.orm.default_entity_manager', getRepository]
#        arguments: ['Domain\Task']

#    task.doctrine_odm.repository:
#        class: Infrastructure\Persistence\DoctrineODM\Task\TaskRepository
#        factory: ['@doctrine.odm.mongodb.document_manager', getRepository]
#        arguments: ['Domain\Task']

#    task.file.repository:
#        class: Infrastructure\Persistence\File\Task\TaskRepository

    task.memory.repository:
        class: Infrastructure\Persistence\Memory\Task\TaskRepository

    task.create_task:
        class: Application\Task\CreateTask
        autowire: true
#        arguments: ['@task.repository']

    task.list_task:
        class: Application\Task\ListTask
        autowire: true
#        arguments: ['@task.repository']

    task.delete_task:
        class: Application\Task\DeleteTask
        autowire: true
#        arguments: ['@task.repository']