services:
    task.frontend.default:
        class: Infrastructure\Delivery\Frontend\TodoBundle\Controller\DefaultController
        autowire: true
#        arguments: ['@task.create_task', '@task.list_task']

#    task.doctrine_orm.repository:
#        class: Infrastructure\Persistence\DoctrineORM\Task\TaskRepository
#        factory: ['@doctrine.orm.default_entity_manager', getRepository]
#        arguments: ['Domain\Task']

#    task.doctrine_odm.repository:
#        class: Infrastructure\Persistence\DoctrineODM\Task\TaskRepository
#        factory: ['@doctrine.odm.mongodb.document_manager', getRepository]
#        arguments: ['Domain\Task']

#    task.file.repository:
#        class: Infrastructure\Persistence\File\Task\TaskRepository

#    task.memory.repository:
#        class: Infrastructure\Persistence\Memory\Task\TaskRepository

    task.repository:
        class: Application\Repository\TaskRepository
        autowire: true

#    adapter.file:
#        class: Infrastructure\Persistence\Adapter\Memory\Adapter

    adapter.doctrine_orm:
        class: Infrastructure\Persistence\Adapter\DoctrineORM\Adapter
        autowire: true

    task.task_service:
        class: Application\Task\TaskService
        autowire: true
#        arguments: ['@task.repository']